version: '3.6'
services:
  traefik:
    image: traefik:1.6
    restart: always
    ports:
      - 127.0.0.1:8080:8080 # UI
      - 127.0.0.1:80:80 # HTTP
      - 127.0.0.1:4443:4443 # HTTPS
    volumes:
      - $PWD/config/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - backend.cert
      - frontend.cert
      - frontend.key
    network_mode: host

  server1:
    image: alextanhongpin/grpc-server:latest
    ports:
      - 127.0.0.1:50051:50051
    environment:
      - PORT=:50051
      - SSL_CERT=/run/secrets/backend.cert
      - SSL_KEY=/run/secrets/backend.key
    hostname: server1
    secrets:
      - backend.cert
      - backend.key
    network_mode: host

  server2:
    image: alextanhongpin/grpc-server:latest
    ports:
      - 127.0.0.1:50052:50052
    environment:
      - PORT=:50052
      - SSL_CERT=/run/secrets/backend.cert
      - SSL_KEY=/run/secrets/backend.key
    hostname: server2
    secrets:
      - backend.cert
      - backend.key
    network_mode: host

  server3:
    image: alextanhongpin/grpc-server:latest
    ports:
      - 127.0.0.1:50053:50053
    environment:
      - PORT=:50053
      - SSL_CERT=/run/secrets/backend.cert
      - SSL_KEY=/run/secrets/backend.key
    hostname: server3
    secrets:
      - backend.cert
      - backend.key
    network_mode: host

  client:
    image: alextanhongpin/grpc-client:latest
    environment:
      - SSL_CERT=/run/secrets/frontend.cert
      - SRV_URL=frontend.local:4443
    secrets:
      - frontend.cert
    network_mode: host

secrets:
  backend.cert: 
    file: ./cert/backend.cert
  backend.key: 
    file: ./cert/backend.key
  frontend.cert: 
    file: ./cert/frontend.cert
  frontend.key: 
    file: ./cert/frontend.key

# networks:
#   grpc: